version: '3'              # compose file 的版本号
services:
  web:
    image: 10.51.2.51:5000/houdongdong/flask-app
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:5000"
    networks:
      - webnet
networks:
  webnet: